# use Java and non-root
dist: trusty
sudo: false
language: Java
jdk: openjdk11

# ignore the virtualenv that Travis creates
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# install the Markdown linting program called mdl
before_install:
  #gr- gem install mdl
  # download gradle as a zip file
  - wget https://services.gradle.org/distributions/gradle-5.1-bin.zip
  - unzip -d $HOME gradle-5.1-bin.zip
  # delete the downloaded file
  - rm -rf gradle-5.1-bin.zip
  # add gradle bin to path at the beginning to ensure it overwrites old gradle
  - export PATH="$HOME/gradle-5.1/bin:$PATH"
  # switch to Python 3.6.3 globally, install python dependencies
  - pyenv global 3.6.3
  - pip install --upgrade pip
  #- pip install proselint
  - pip install pipenv
  # do not allow Travis to use standard error for debugging purposes
  - unset _JAVA_OPTIONS

# cache to improve build speed
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# delete any cached version of GatorGrader and require a fresh installation
before_script:
  - rm -rf $HOME/.local/share/gatorgrader

# run checks on the README file with mdl and proselint
# run checks on a student's Java code through gradle and GatorGrader
# run checks on a student's Markdown writing through GatorGrader
# note: "gradle grade" will install GatorGrader and run all checks
script:
  # lint the assignment's documentation
  #- mdl README.md
  #- proselint README.md
  # Java: see build.gradle
  - gradle --version
  - gradle clean
  - gradle check
  - gradle build
  - gradle run
  # GatorGrader: see config/gatorgrader.yml
  - gradle grade
